#!/bin/sh
#
# @name HIL Quadcopter w GIMBAL
#
# @type Simulation
# @class Copter


sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
    param set MC_PITCH_P 7.69
    param set MC_PITCHRATE_P 0.266
    param set MC_PITCHRATE_D 0.0004
    param set MC_PITCHRATE_I 0.331

param set MC_ROLL_P 6.95
param set MC_ROLLRATE_P 0.484
param set MC_ROLLRATE_D 0.0026
param set MC_ROLLRATE_I 0.332

param set MC_YAW_P 5.00
param set MC_YAWRATE_P 0.60
param set MC_YAWRATE_D 0.0
param set MC_YAWRATE_I 0.2

param set MPC_XY_VEL_MAX 6
param set MPC_MANTHR_MIN 0.100000001490116
param set MPC_THR_HOVER 0.779999971389771



        param set TRIG_INTERFACE 1
        param set TRIG_MODE 0

        param set MNT_MODE_IN 3
        param set MNT_DO_STAB 0

        param set MAV_PROTO_VER 1
fi

set MAV_TYPE 2

set MIXER quad_w
